/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 office_building.gltf --transform 
Files: office_building.gltf [7.08MB] > office_building-transformed.glb [656.69KB] (91%)
Author: Nikitos & 3130 (https://sketchfab.com/vrcityphoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-building-af9782245c134c21ae0c8df7f57077e6
Title: Office building
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/transformed/office_building-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BLD_OFFICE_00_walls_exterior_0.geometry}
        material={materials.PaletteMaterial001}
        position={[26.83, -106.461, 47.865]}
        rotation={[-Math.PI / 2, 0, -1.688]}
      />
      <mesh
        geometry={nodes.BLD_OFFICE_01_glass_0.geometry}
        material={materials.PaletteMaterial002}
        position={[26.83, -106.461, 47.865]}
        rotation={[-Math.PI / 2, 0, -1.688]}
      />
      <mesh
        geometry={nodes["BLD_OFFICE_03_Material_#17_0"].geometry}
        material={materials.PaletteMaterial003}
        position={[148.796, -22.991, 19.777]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.BLD_OFFICE_05_walls_BLD_OFFICE_05_0.geometry}
        material={materials.walls_BLD_OFFICE_05}
        position={[26.83, -106.461, 47.865]}
        rotation={[-Math.PI / 2, 0, -1.688]}
      />
      <mesh
        geometry={nodes.BLD_OFFICE_06_w2_0.geometry}
        material={materials.material}
        position={[-22.601, 641.03, 116.251]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.office_chairs00_Color_007_0.geometry}
        material={materials.PaletteMaterial004}
        position={[30.135, -93.889, -7.738]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={6.108}
      />
      <mesh
        geometry={nodes.BLD_OFFICE_08_Blinds_Roman_Hobbled_Blue_0.geometry}
        material={materials.Blinds_Roman_Hobbled_Blue}
        position={[226.315, -45.948, 49.915]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-6.108, 6.108, 6.108]}
      />
      <instancedMesh
        args={[
          nodes.office_chairs02__0.geometry,
          materials.PaletteMaterial001,
          20,
        ]}
        instanceMatrix={nodes.office_chairs02__0.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/transformed/office_building-transformed.glb");
